[Inductor] register `target_code` in `input_codes` tracker (#189206)
Otherwise `reset` appears to leave precompile entries which breaks e.g.,

```
Traceback (most recent call last):
  File "/usr/lib/python3.12/unittest/case.py", line 58, in testPartExecutor
    yield
  File "/usr/lib/python3.12/unittest/case.py", line 634, in run
    self._callTestMethod(testMethod)
  File "/usr/lib/python3.12/unittest/case.py", line 589, in _callTestMethod
    if method() is not None:
       ^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/torch/testing/_internal/common_utils.py", line 3590, in wrapper
    method(*args, **kwargs)
  File "/usr/local/lib/python3.12/dist-packages/torch/testing/_internal/common_utils.py", line 618, in instantiated_test
    test(self, **param_kwargs)
  File "/usr/lib/python3.12/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/pytorch/pytorch/test/inductor/test_codecache.py", line 1143, in test_cache_hot_load_caching_precompile
    self.assertEqual(len(cache_info.autotune_artifacts), autotune_expect)
  File "/usr/local/lib/python3.12/dist-packages/torch/_dynamo/test_case.py", line 129, in assertEqual
    return super().assertEqual(x, y, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/torch/testing/_internal/common_utils.py", line 4608, in assertEqual
    raise error_metas.pop()[0].to_error(  # type: ignore[index]
AssertionError: Scalars are not equal!

Expected 2 but got 4.
Absolute difference: 2
Relative difference: 1.0

To execute this test, run the following from the base repo dir:
    python test/inductor/test_codecache.py TestFxGraphCache.test_cache_hot_load_caching_precompile_dynamic_False_device_cuda_bfloat16
```

    (either the test needs to be run with repeat or neighboring tests which exercise the caching need to be run to repro)

    authored with codex

Pull Request resolved: https://github.com/pytorch/pytorch/pull/189206
Approved by: https://github.com/williamwen42