[inductor] Fix circular import between quantized_lowerings and lowering (#188679)
Similar change to https://github.com/pytorch/pytorch/pull/182189

Encountered this problem in this CI job: https://github.com/pytorch/pytorch/actions/runs/28511622872/job/84516440058?pr=186204.

```txt
=================================== FAILURES ===================================
____________________ TestImports.test_circular_dependencies ____________________
Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/test/test_testing.py", line 2518, in test_circular_dependencies
    mod = importlib.import_module(mod_name)
  File "/opt/conda/envs/py_3.10/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/_inductor/quantized_lowerings.py", line 7, in <module>
    from . import config, lowering
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/_inductor/lowering.py", line 9345, in <module>
    quantized_lowerings.register_quantized_ops()
AttributeError: partially initialized module 'torch._inductor.quantized_lowerings' has no attribute 'register_quantized_ops' (most likely due to a circular import)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/test/test_testing.py", line 2520, in test_circular_dependencies
    raise RuntimeError(f"Failed to import {mod_name}: {e}") from e
RuntimeError: Failed to import torch._inductor.quantized_lowerings: partially initialized module 'torch._inductor.quantized_lowerings' has no attribute 'register_quantized_ops' (most likely due to a circular import)

To execute this test, run the following from the base repo dir:
    PYTORCH_TEST_WITH_ROCM=1 python test/test_testing.py TestImports.test_circular_dependencies
```

Pull Request resolved: https://github.com/pytorch/pytorch/pull/188679
Approved by: https://github.com/Skylion007